### ISSUE TITLE
Crash after sleep

### ISSUE THREAD

**Issue by andsat** [antoinepirlot/Satunes#781]
New version 2.1.0 crashes when attempting to view music library via "musics" menu. 

Also unresponsive on Android Auto interface in car.

**Comment by antoinepirlot** [comment]
Hello,

Thanks for reporting.

This issue has been fixed in v2.1.1, it will arrive on Fdroid soon or you can download it now from GitHub or in-app.

**Comment by andsat** [comment]
This wasn't fixed. I believe it was related to a corrupt m4a file. It stopped crashing when I cleaned up my library of incomplete downloads. Seems to be an error handling issue.

**Comment by antoinepirlot** [comment]
Indeed, I've begun to have this issue, I thought it was related to Android Auto as it stopped crash for while.

I will check this out.

**Comment by antoinepirlot** [comment]
> This wasn't fixed. I believe it was related to a corrupt m4a file. It stopped crashing when I cleaned up my library of incomplete downloads. Seems to be an error handling issue.

it's related to corrupt m4a files as the issue happens with my dataset that doesn't contain any m4a files or corrupted files.

**Comment by antoinepirlot** [comment]
Caused by playbackController var in PlaybackService in onCreate function. The playbackController was got when not created and throws an error that's expected.
Removing and checking PlaybackManager values instead of using the inclass playbackController.

**Comment by antoinepirlot** [comment]
Seems to be fixed + Satunes seems to stay alive for a moment after pause.
